export const mockUpcomingResponse = {
  dates: {
    maximum: '2021-03-17',
    minimum: '2021-02-24',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg',
      genre_ids: [53, 80],
      id: 602269,
      original_language: 'en',
      original_title: 'The Little Things',
      overview:
        'Deputy Sheriff Joe "Deke" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who\'s terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke\'s past, uncovering disturbing secrets that could threaten more than his case.',
      popularity: 1278.178,
      poster_path: '/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg',
      release_date: '2021-01-28',
      title: 'The Little Things',
      video: false,
      vote_average: 6.4,
      vote_count: 318,
    },
    {
      adult: false,
      backdrop_path: '/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg',
      genre_ids: [878, 28],
      id: 560144,
      original_language: 'en',
      original_title: 'Skylines',
      overview:
        "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
      popularity: 856.87,
      poster_path: '',
      release_date: '2020-10-25',
      title: 'Skylines',
      video: false,
      vote_average: 5.7,
      vote_count: 171,
    },
  ],
  total_pages: 12,
  total_results: 234,
}

export type MockUpcomingResponse = typeof mockUpcomingResponse

export const mockNowPlayingResponse = {
  dates: {
    maximum: '2021-02-25',
    minimum: '2021-01-08',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
      genre_ids: [14, 28, 12],
      id: 464052,
      original_language: 'en',
      original_title: 'Wonder Woman 1984',
      overview:
        'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
      popularity: 1955.44,
      poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
      release_date: '2020-12-16',
      title: 'Wonder Woman 1984',
      video: false,
      vote_average: 6.9,
      vote_count: 3718,
    },
  ],
  total_pages: 39,
  total_results: 774,
}

export type MockNowPlayingResponse = typeof mockNowPlayingResponse

export const mockMoviesSearchResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/t19hP0GCPA20FxR6k7BTnPSETBb.jpg',
      genre_ids: [35],
      id: 516151,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Brad Upton: Will Be Funny For Money',
      overview:
        "Brad Upton first stepped on stage in September of 1984 and he's never looked back. This ex-grade school teacher is now in his 30th year of comedy and is nearing 6000 lifetime performances.",
      popularity: 5.46,
      poster_path: '/kaLHwS1bqgvSlplKeqH7b1FFfDT.jpg',
      release_date: '2017-04-20',
      title: 'Brad Upton: Will Be Funny For Money',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      first_air_date: '2000-03-27',
      genre_ids: [18, 10766],
      id: 5080,
      media_type: 'tv',
      name: 'Doctors',
      origin_country: ['GB'],
      original_language: 'en',
      original_name: 'Doctors',
      overview:
        "Set in the fictional Midlands town of Letherbridge, defined as being close to the city of Birmingham, this soap opera follows the staff and families of a doctor's surgery.",
      poster_path: '/thZKqMWevSJVTeAiedy40umvz11.jpg',
      vote_average: 4.6,
      vote_count: 27,
    },
    {
      adult: false,
      gender: 2,
      id: 287,
      known_for: [
        {
          adult: false,
          backdrop_path: '/52AfXWuXCHn3UjD17rBruA9f5qb.jpg',
          genre_ids: [18],
          id: 550,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Fight Club',
          overview:
            'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
          poster_path: '/8kNruSfhk5IoE4eZOc4UpvDn6tq.jpg',
          release_date: '1999-10-15',
          title: 'Fight Club',
          video: false,
          vote_average: 8.4,
          vote_count: 21115,
        },
        {
          adult: false,
          backdrop_path: '/bPnPsyo09tLRnTOb7AlsBsgnbhP.jpg',
          genre_ids: [18, 28, 53, 10752],
          id: 16869,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Inglourious Basterds',
          overview:
            'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.',
          poster_path: '/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg',
          release_date: '2009-08-18',
          title: 'Inglourious Basterds',
          video: false,
          vote_average: 8.2,
          vote_count: 16323,
        },
        {
          adult: false,
          backdrop_path: '/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg',
          genre_ids: [80, 9648, 53],
          id: 807,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Se7en',
          overview:
            'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
          poster_path: '/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
          release_date: '1995-09-22',
          title: 'Se7en',
          video: false,
          vote_average: 8.3,
          vote_count: 14676,
        },
      ],
      known_for_department: 'Acting',
      media_type: 'person',
      name: 'Brad Pitt',
      popularity: 23.634,
      profile_path: '/ajNaPmXVVMJFg9GWmu6MJzTaXdV.jpg',
    },
  ],
  total_pages: 186,
  total_results: 3669,
}

export type MockMoviesSearchResponse = typeof mockMoviesSearchResponse

export const mockMovieInfoResponse = {
  adult: false,
  backdrop_path: '/5GbkL9DDRzq3A21nR7Gkv6cFGjq.jpg',
  belongs_to_collection: null,
  budget: 0,
  genres: [
    {
      id: 35,
      name: 'Comedy',
    },
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 10749,
      name: 'Romance',
    },
  ],
  homepage: 'https://www.focusfeatures.com/emma',
  id: 556678,
  imdb_id: 'tt9214832',
  original_language: 'en',
  original_title: 'Emma.',
  overview:
    'In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.',
  popularity: 74.727,
  poster_path: '/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg',
  production_companies: [
    {
      id: 10163,
      logo_path: '/16KWBMmfPX0aJzDExDrPxSLj0Pg.png',
      name: 'Working Title Films',
      origin_country: 'GB',
    },
    {
      id: 10146,
      logo_path: '/xnFIOeq5cKw09kCWqV7foWDe4AA.png',
      name: 'Focus Features',
      origin_country: 'US',
    },
    {
      id: 10338,
      logo_path: '/el2ap6lvjcEDdbyJoB3oKiYgXu9.png',
      name: 'Perfect World Pictures',
      origin_country: 'CN',
    },
    {
      id: 2376,
      logo_path: '/yeNoWmSHZfvKsBYuL8uTRE4LPdQ.png',
      name: 'Blueprint Pictures',
      origin_country: 'GB',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'GB',
      name: 'United Kingdom',
    },
  ],
  release_date: '2020-02-13',
  revenue: 25155355,
  runtime: 125,
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: '/wztoDoglCOuiEfzl1FS6mglBioF.jpg',
        genre_ids: [18],
        id: 410117,
        original_language: 'en',
        original_title: 'Lady Macbeth',
        overview:
          "Rural England, 1865. Katherine, suffocated by her loveless marriage to a bitter man and restrained by his father's tyranny, unleashes an irresistible force within her, so powerful that she will stop at nothing to get what she wants.",
        popularity: 16.25,
        poster_path: '/xWTJbhTwSTJmhLlX5xAOxPhdnXc.jpg',
        release_date: '2016-12-12',
        title: 'Lady Macbeth',
        video: false,
        vote_average: 6.5,
        vote_count: 465,
      },
    ],
    total_pages: 32,
    total_results: 629,
  },
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Love knows best.',
  title: 'Emma.',
  video: false,
  vote_average: 7.1,
  vote_count: 720,
}

export type MockMovieInfoResponse = typeof mockMovieInfoResponse

export const mockTvShowInfoResponse = {
  backdrop_path: '/df4V825ahcsw4qKuFTEefippoCG.jpg',
  created_by: [
    {
      credit_id: '60291018a6725400426a5e99',
      gender: 2,
      id: 7624,
      name: 'Stan Lee',
      profile_path: '/nGjBAc25C3LT23NqeOfY1pCcax8.jpg',
    },
    {
      credit_id: '6029102f92e55b003f5d5b36',
      gender: 2,
      id: 7625,
      name: 'Steve Ditko',
      profile_path: '/dfdSdCN8Zb9MD5qSkpMseze4n8H.jpg',
    },
  ],
  episode_run_time: [22],
  first_air_date: '1994-11-19',
  genres: [
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 10759,
      name: 'Action & Adventure',
    },
  ],
  homepage: '',
  id: 888,
  in_production: false,
  languages: ['en'],
  last_air_date: '1998-01-31',
  last_episode_to_air: {
    air_date: '1998-01-31',
    episode_number: 13,
    id: 48849,
    name: 'Spider Wars (2): Farewell, Spider-Man',
    overview:
      'Spider-Man is sent through several dimensions trying to fix time and seal away Spider-Carnage. Peter meets his would be girlfriend Gwen Stacey and Stan Lee.',
    production_code: '',
    season_number: 5,
    still_path: '/mSvy3PBKsjxYvik41UI1m6DtKXT.jpg',
    vote_average: 8.5,
    vote_count: 2,
  },
  name: 'Spider-Man',
  networks: [
    {
      id: 19,
      logo_path: '/1DSpHrWyOORkL9N2QHX7Adt31mQ.png',
      name: 'FOX',
      origin_country: 'US',
    },
    {
      id: 2686,
      logo_path: '/rUb71E91POVCxpXGJ49pf6m8Ukk.png',
      name: 'Fox Kids',
      origin_country: 'US',
    },
  ],
  next_episode_to_air: null,
  number_of_episodes: 65,
  number_of_seasons: 5,
  origin_country: ['US'],
  original_language: 'en',
  original_name: 'Spider-Man',
  overview:
    'Bitten by a radioactive spider, Peter Parker develops spider-like superpowers. He uses these to fight crime while trying to balance it with the struggles of his personal life.',
  popularity: 60.726,
  poster_path: '/wXthtEN5kdWA1bHz03lkuCJS6hA.jpg',
  production_companies: [
    {
      id: 54851,
      logo_path: null,
      name: 'New World Entertainment Films',
      origin_country: '',
    },
    {
      id: 62042,
      logo_path: null,
      name: 'Genesis Entertainment',
      origin_country: '',
    },
    {
      id: 19551,
      logo_path: '/2WpWp9b108hizjHKdA107hFmvQ5.png',
      name: 'Marvel Enterprises',
      origin_country: 'US',
    },
    {
      id: 2301,
      logo_path: '/qdPhBEP8sjK3Eb3rKc94554gcZt.png',
      name: 'Marvel Productions',
      origin_country: 'US',
    },
    {
      id: 7164,
      logo_path: '/vHsaqTkQ2ZTbdqrCA272YahoVlg.png',
      name: 'TMS Entertainment',
      origin_country: 'JP',
    },
  ],
  production_countries: [],
  seasons: [
    {
      air_date: '2004-06-19',
      episode_count: 1,
      id: 2571,
      name: 'Specials',
      overview: '',
      poster_path: null,
      season_number: 0,
    },
    {
      air_date: '1994-11-19',
      episode_count: 13,
      id: 2572,
      name: 'Season 1',
      overview: '',
      poster_path: '/5311wSCVVXZgoCCbjszm4tt6vDz.jpg',
      season_number: 1,
    },
    {
      air_date: '1995-09-09',
      episode_count: 14,
      id: 2570,
      name: 'Season 2',
      overview: '',
      poster_path: '/kLH7jvpZX5om5kRf0PnkknqdRnn.jpg',
      season_number: 2,
    },
    {
      air_date: '1996-04-27',
      episode_count: 14,
      id: 2568,
      name: 'Season 3',
      overview: '',
      poster_path: '/1vqVLjM1m7jJ3xH7WcjNLgt50mP.jpg',
      season_number: 3,
    },
    {
      air_date: '1997-02-01',
      episode_count: 11,
      id: 2569,
      name: 'Season 4',
      overview: '',
      poster_path: '/7WFnsoEj89jS2m67r04hvSy0PrY.jpg',
      season_number: 4,
    },
    {
      air_date: '1997-09-12',
      episode_count: 13,
      id: 2573,
      name: 'Season 5',
      overview: '',
      poster_path: '/8GY0gSOOoSrTB3tRyrpJ2Yi4Cny.jpg',
      season_number: 5,
    },
  ],
  similar: {
    page: 1,
    results: [
      {
        backdrop_path: '/4QnFxk03yAn7U2ZTL5oMCCqxlPc.jpg',
        first_air_date: '1992-09-05',
        genre_ids: [10759, 16, 18, 9648],
        id: 2098,
        name: 'Batman: The Animated Series',
        origin_country: ['US'],
        original_language: 'en',
        original_name: 'Batman: The Animated Series',
        overview:
          'Vowing to avenge the murder of his parents, Bruce Wayne devotes his life to wiping out crime in Gotham City as the masked vigilante "Batman".',
        popularity: 103.611,
        poster_path: '/7ZsnVtDtkMiuMirKSZdaLaU4wMR.jpg',
        vote_average: 8.3,
        vote_count: 844,
      },
    ],
    total_pages: 19,
    total_results: 373,
  },
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Ended',
  tagline: '',
  type: 'Scripted',
  vote_average: 8.2,
  vote_count: 478,
}

export type MockTvShowInfoResponse = typeof mockTvShowInfoResponse
